### ISSUE TITLE
Javascript Java Interopt

### ISSUE THREAD

**Issue by norzak** [java2script/java2script#122]
Is there any documentation or support for a Javascript/Java Interopt API?

**Comment by BobHanson** [comment]
Yes.  Start with the readme file at
https://github.com/java2script/java2script

There is also a recently written detailed discussion
at sources/net.sf.j2s.java.core/doc/graphics.txt

Mostly I suggest after you look those over that we talk about your
application and let me give you some idea of the issues that might be
involved for you.

Bob Hanson

**Comment by norzak** [comment]
thanks for the suggestions, looks like I will just pass.
