### ISSUE TITLE
Test_9 -- initialization runs twice; inner object may not be assigned correctly

### ISSUE THREAD

**Issue by BobHanson** [java2script/java2script#13]
// Bob Hanson note 11/28/16

// This test finds two bugs in j2slib: 
// 1) initializsers are being run twice
// 2) incorrect object assignment is seen in inner classes that 
//    extend a class that the outer object also extends.
//
// This is fixed for j2sSwingJS 11/28/16

[https://chemapps.stolaf.edu/swingjs/j2sbugs/Test_9.java](url)

**Comment by abego** [comment]
For your convenience here the test file also in github: [Test_9.java](https://github.com/zhourenjian/java2script/files/616932/Test_9.java.txt)

**Comment by BobHanson** [comment]
all initialization is perfectly aligned with Java now
