### ISSUE TITLE
"j2slib.z.js" FileNotFoundException when building j2slib the first time

### ISSUE THREAD

**Issue by abego** [java2script/java2script#15]
## Steps to reproduce

- go to `sources/net.sf.j2s.lib`
- make sure no directory `j2slib` exists. (run `rm -r j2slib` if necessary)
- run `ant -f build/build.xml`

The build will report these errors for the target `j2s.pack.core`:

- `[java] java.io.FileNotFoundException: /Users/ub/work/project/sd/thirdparty/java2script(java2script)/sources/net.sf.j2s.lib/build/../../net.sf.j2s.lib/j2slib/j2slib.z.js (No such file or directory)`
- `[java] java.io.FileNotFoundException: /Users/ub/work/project/sd/thirdparty/java2script(java2script)/sources/net.sf.j2s.lib/build/../../net.sf.j2s.lib/j2slib/j2slib.src.z.js (No such file or directory)`
- `[java] java.io.FileNotFoundException: /Users/ub/work/project/sd/thirdparty/java2script(java2script)/sources/net.sf.j2s.lib/build/../../net.sf.j2s.lib/j2slib/j2slib.swt.z.js (No such file or directory)`
- `[java] java.io.FileNotFoundException: /Users/ub/work/project/sd/thirdparty/java2script(java2script)/sources/net.sf.j2s.lib/build/../../net.sf.j2s.lib/j2slib/j2slibcore.z.js (No such file or directory)`

[(Complete log of initial run)](https://github.com/java2script/java2script/files/1100409/log1.txt)

## Workaround

When running `ant -f build/build.xml` a second time the errors are gone.

[(Complete log of second run)](https://github.com/java2script/java2script/files/1100412/log2.txt)

## Possible Solution

It looks like the order in the processing needs to be changed. The compacted files are referenced before they are created.

**Comment by abego** [comment]
Once this issue is fixed also update j2slib documentation at https://github.com/java2script/java2script/wiki/BuildingJ2SLib

**Comment by BobHanson** [comment]
no longer applicable - not using j2slib
