### ISSUE TITLE
Boolean.FALSE fails to set Boolean value to false.

### ISSUE THREAD

**Issue by upahsan** [java2script/java2script#18]
This issue is present in both 2.0.0 and 3.1.1

Code:
`
public class Test_Boolean {

    public static void main(String[] args) {
        Boolean b = Boolean.FALSE;
        System.out.println(Boolean.FALSE ? "FAILED" : "OK");
        System.out.println(b? "FAILED" : "OK");
    }

}
`

This should print OK for both tests but it prints FAILED when run through j2s.

**Comment by abego** [comment]
Testcase `net.sf.j2s.test.junit.issue.Issue18Test` added to cover this issue.

**Comment by abego** [comment]
Interestingly using `Boolean.FALSE` in an `if` statement works fine, as does a `Boolean.FALSE` in `assertFalse(...)`.

**Comment by BobHanson** [comment]
no longer an issue
