### ISSUE TITLE
Provide a standalone and ready to use distribution like CheerpJ

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [java2script/java2script#218]
I only want to be able to run my favorite Java based applications on the browser as effortless as possible. I don't want to build teavm from source myself. An installer that included everything and ready to use like CheerpJ is greatly appreciated!

https://leaningtech.com/download-cheerpj/

p/s: I don't know how to use Eclipse and I don't want to use it too!

**Comment by BobHanson** [comment]
It's a different philosophy. We are producing fully functional Java and JavaScript. It requires Eclipse, and it requires some adjustments to the Java to be compatible with JavaScript. Sorry I cannot help you. Why not just use CheerpJ?

**Comment by 2dpdlja496or43iq** [comment]
> It's a different philosophy. We are producing fully functional Java and JavaScript. It requires Eclipse, and it requires some adjustments to the Java to be compatible with JavaScript. Sorry I cannot help you. Why not just use CheerpJ?

CheerpJ only supports Java 8.
