### ISSUE TITLE
How to compile Pixelitor to JavaScript?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [java2script/java2script#219]
https://github.com/lbalazscs/Pixelitor

**Comment by BobHanson** [comment]
Difficult to impossible.

https://github.com/lbalazscs/Pixelitor/tree/master/src/main/java/pixelitor

Pixelitor requires Java 17+ to compile (for whatever reason) 
Also, it has about a dozen dependencies that would have to be tracked down and followed extensively.
