### ISSUE TITLE
Java 9 not supported

### ISSUE THREAD

**Issue by abego** [java2script/java2script#39]
When the Java project is using a Java 9 JRE Eclipse shows these errors:

    - The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project
    - The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files

When changing to a Java 8 JRE the errors disappear.

**Comment by BobHanson** [comment]
Not clear what the issue is there; so far we are supporting Java 8.

**Comment by BobHanson** [comment]
Java 9 and 10 classes and methods are being added as needed.
