### ISSUE TITLE
Generating j2slib.zip from scratch

### ISSUE THREAD

**Issue by infinity0** [java2script/java2script#8]
Hi, I'm trying to figure out how to generate j2slib.zip from scratch - i.e. without reusing files from inside the j2slib.zip already in the git repository. I can regenerate most of it, however there are some differences. I am using the j2s-eclipse-3.8 branch, and I'm using the Makefile in PR #6 to do the build. Roughly, what it does is:
1. Delete `sources/net.sf.j2s.lib/j2slib.zip`.
2. Build the plugin projects:
   1. net.sf.j2s.core
   2. net.sf.j2s.ajax
   3. net.sf.j2s.ui
   4. net.sf.j2s.lib
3. Install the above to Eclipse
4. Build the j2s projects:
   1. net.sf.j2s.ajax
   2. net.sf.j2s.java.core
   3. net.sf.j2s.java.org.eclipse.swt
5. Runs the `j2s.pack.lib` target in `sources/net.sf.j2s.lib/build/build.xml`.

The build succeeds, but my j2slib.zip is a bit different. Here are the differences:

**Unexplained missing files** (not in my j2slib.zip, but in the one in git):

~~~~
-java/io/FileInputStream.js
-java/io/FileOutputStream.js
-java/lang/Object.js
-java/net/URL.js
~~~~

Missing, but `git grep -- sources` suggests that nothing is using them:

~~~~
-net/sf/j2s/ajax/PipeManager.js
-net/sf/j2s/ajax/PipeObject.js
~~~~

Missing, but `git log -p` shows you're no longer building these, so I don't need to either:

~~~~
-java/error.z.js
-java/lang/reflect.z.js
-net/sf/j2s/ajax/simple.z.js
-org/eclipse/swt/custom/images/**
-org/eclipse/swt/events.z.js
-org/eclipse/swt/more.z.js # moved to widgets
-org/eclipse/swt/layout/FillLayout.z.js
-org/eclipse/swt/layout/GridLayout.z.js
-org/eclipse/swt/widgets/Common.z.js
-org/eclipse/swt/widgets/DesktopListener.js
-org/eclipse/swt/widgets/Menu.z.js
-org/eclipse/swt/widgets/TabFolder.z.js
-org/eclipse/swt/widgets/Tray.z.js
~~~~

Extra files on my side, probably just a part of the newer version of the source code:

~~~~
+j2slib.src.z.js
+j2slib.swt.z.js
+net/sf/j2s/ajax/annotation/SimpleComment.js
+net/sf/j2s/ajax/annotation/SimpleIn.js
+net/sf/j2s/ajax/annotation/SimpleInOut.js
+net/sf/j2s/ajax/annotation/SimpleOut.js
+net/sf/j2s/ajax/ISimpleCacheable.js
+net/sf/j2s/ajax/ISimpleCometable.js
+net/sf/j2s/ajax/ISimpleConstant.js
+net/sf/j2s/ajax/ISimpleEnum.js
+net/sf/j2s/ajax/ISimpleGeoLocationBinding.js
+net/sf/j2s/ajax/ISimpleGeoLocation.js
+net/sf/j2s/ajax/ISimplePipePriority.js
+net/sf/j2s/ajax/ISimpleRequestBinding.js
+net/sf/j2s/ajax/ISimpleRequestInfoBinding.js
+net/sf/j2s/ajax/ISimpleRequestInfo.js
+net/sf/j2s/ajax/SimpleClassLoader.js
+net/sf/j2s/ajax/SimpleFactory.js
+net/sf/j2s/ajax/SimpleNamedThreadFactory.js
+net/sf/j2s/ajax/SimplePipeSequence.js
+net/sf/j2s/ajax/SimpleRPCUtils.js
+net/sf/j2s/ajax/SimpleSource4Java.js
+net/sf/j2s/ajax/SimpleSource4ObjectiveC.js
+net/sf/j2s/ajax/SimpleThreadConfig.js
+net/sf/j2s/ajax/SimpleThreadHelper.js
+net/sf/j2s/ajax/SimpleThreadPoolExecutor.js
+net/sf/j2s/ajax/SourceUtils.js
+net/sf/j2s/annotation/J2SDebug.js
+net/sf/j2s/annotation/J2SIgnoreImport.js
+net/sf/j2s/annotation/J2SIgnore.js
+net/sf/j2s/annotation/J2SIngoreSuperConstructor.js
+net/sf/j2s/annotation/J2SKeep.js
+net/sf/j2s/annotation/J2SNative.js
+net/sf/j2s/annotation/J2SNativeSrc.js
+net/sf/j2s/annotation/J2SOptionalImport.js
+net/sf/j2s/annotation/J2SOverride.js
+net/sf/j2s/annotation/J2SPrefix.js
+net/sf/j2s/annotation/J2SRequireImport.js
+net/sf/j2s/annotation/J2SSuffix.js
+net/sf/j2s/store/CookieStore.js
+net/sf/j2s/store/HTML5LocalStorage.js
+net/sf/j2s/store/INIFileStore.js
+net/sf/j2s/store/IStore.js
+net/sf/j2s/store/SimpleStore.js
+net/sf/j2s/store/xss-cookie.html
+net/sf/j2s/store/XSSCookieStore.js
+org/eclipse/swt/dnd.z.js
+org/eclipse/swt/widgets/images/packed.gif
+org/eclipse/swt/widgets/more.z.js
~~~~

Could you tell me the reason behind these differences, and how I can generate j2slib to exact match the one distributed in git?

**Comment by infinity0** [comment]
One strange thing is, in step (4.1) `sources/net.sf.j2s.ajax/bin/net/sf/j2s/ajax/ARunnable.class` is getting built, but not the corresponding `.js` file. Yet `bin/net/sf/j2s/ajax/ARunnable.js` is listed in `sources/net.sf.j2s.ajax/.j2s`.

**Comment by infinity0** [comment]
OK, I figured out why I was missing some ajax files - because I need to uncomment and comment some lines in its `.project` file before trying the J2S build. However, there are still some things missing. I've updated the list in the original post.

**Comment by infinity0** [comment]
I figured out how to build `j2slib/j2slibcore.z.js` and `j2slib/j2slib.z.js` - it was because you need to create a `j2slib` directory or else `build.xml` fails silently. I've updated my pull request #6 to reflect this.

By looking at the git logs, I can also see that some old files are now obsolete. I've updated the first post to describe this new situation.

However, there are still a few last remaining unexplained missing files:

~~~~
-java/io/FileInputStream.js
-java/io/FileOutputStream.js
-java/lang/Object.js
-java/net/URL.js
~~~~

I guess I can just copy the corresponding java files from some version of the JDK, then these will be generated automatically. Could you tell me which version, please?

Or are you somehow representing these files using a different magical method in this newer versions of J2S?

**Comment by BobHanson** [comment]
no longer relevant
